# Generated by Django 4.2.5 on 2023-12-15 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('salary', models.PositiveIntegerField(verbose_name='Salary')),
                ('skill', models.TextField(verbose_name='Skills')),
                ('duty', models.TextField(verbose_name='Duty')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Patronymic')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('skills', models.TextField(verbose_name='Skill')),
                ('experience', models.TextField(verbose_name='Exp')),
                ('education', models.TextField(verbose_name='Education')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
